name: Docker Image CI for GHCR

on:
  push:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Push the Image
      run: |
        docker login --username jaredseavyhodge --password ${{ secrets.GHCR_PAT }} ghcr.io
        docker build . -t ghcr.io/jaredseavyhodge/abiotic-factor:latest
        docker push ghcr.io/jaredseavyhodge/abiotic-factor:latest
      